# Álgebra Lineal con Python 03


Recordemos que si damos $n\times m$ números reales, entonces podemos crear un arreglo (una matriz):
$$A_{m\times n}=\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}$$

y al conjunto de matrices con coeficientes en $\mathbb{R}$ lo denotamos $\text{Mat}_{m\times n}(\mathbb{R})$.


In [1]:
type(2), type(2.0), type("2") # La función type(obj) nos dice el tipo de objeto con el que se está trabajando.

(int, float, str)

### Variables
$$\text{nombre} = \text{objeto}$$

Debug: $\text{print(variable)}$

1. Suma de matrices

$$\begin{pmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\ a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} & a_{m2} & \cdots & a_{mn} \end{pmatrix} + \begin{pmatrix} b_{11} & b_{12} & \cdots & b_{1n} \\ b_{21} & b_{22} & \cdots & b_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ b_{m1} & b_{m2} & \cdots & b_{mn} \end{pmatrix} = \begin{pmatrix} a_{11} + b_{11} & a_{12} + b_{12} & \cdots & a_{1n} + b_{1n} \\ a_{21} + b_{21} & a_{22} + b_{22} & \cdots & a_{2n} + b_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} + b_{m1} & a_{m2} + b_{m2} & \cdots & a_{mn} + b_{mn} \end{pmatrix}$$

2. Multiplicación de matrices

$$\begin{pmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{pmatrix} \times \begin{pmatrix} b_{11} & b_{12} \\ b_{21} & b_{22} \end{pmatrix} = \begin{pmatrix} a_{11}b_{11} + a_{12}b_{21} & a_{11}b_{12} + a_{12}b_{22} \\ a_{21}b_{11} + a_{22}b_{21} & a_{21}b_{12} + a_{22}b_{22} \end{pmatrix} $$

### Listas

$L=[a_{0}, a_{1}, \dots, a_{n-1}]$

In [2]:
# Vamos a generar 3 listas
L = [1, 2, 3, 4, 5]

M = [6, 7, 8, 9 , 10]

N = [11, 12, 13]

print(L)
print(M)  # me muestra el resultado
print(N)

[1, 2, 3, 4, 5]
[6, 7, 8, 9, 10]
[11, 12, 13]


In [3]:
# Que objeto es
type(L)

list

In [4]:
# Transformación de listas
L_set = set(L)

L_set

{1, 2, 3, 4, 5}

In [5]:
L_lista = list(L_set)
L_lista

[1, 2, 3, 4, 5]

In [6]:
L + M # concatena (no realiza operaciones vectoriales).

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [7]:
L + M + N

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

### NumPy

- Un vector = arreglo 1D en Python
- Una matriz = arreglo 2D en Python

In [8]:
# Llamamos a la libreria para hacer operaciones vectoriales
import numpy as np

In [9]:
L_vector = np.array(L) # Convertir una lista en un vector. La funcón "np.array" es la que hace esta transformación

L_vector

array([1, 2, 3, 4, 5])

In [10]:
type(L_vector)

numpy.ndarray

In [11]:
# Aqui se hacen conversiones de listas a vectores
M_vector = np.array(M)

N_vector = np.array(N)

print(M_vector)
print(N_vector)

[ 6  7  8  9 10]
[11 12 13]


In [12]:
# Aquí se ve el tamaño de elector (número de elementos)
len(L_vector), len(M_vector), len(N_vector)

(5, 5, 3)

In [13]:
L_vector + M_vector # suma vectorial

array([ 7,  9, 11, 13, 15])

### Con esto, ya se puede sumar como vectores, los cuáles tengan el mismo número de elementos

## Creando matrices con NumPy: El método `solve( , )`



Problema de Compra de Frutas

Luis desea comprar manzanas y naranjas para hacer jugo. En el mercado, el precio del kilo de manzanas es de $20$ pesos, y el kilo de naranjas es de $15$ pesos. Con un presupuesto de $150$ pesos, Luis quiere comprar un total de $10$ kilos de frutas. Se pide determinar cuántos kilos de manzanas y cuántos kilos de naranjas debe comprar para cumplir con su presupuesto y la cantidad deseada de frutas.

Planteamiento del problema

Se define \(x\) como la cantidad de kilos de manzanas y \(y\) como la cantidad de kilos de naranjas que Luis comprará. El sistema de ecuaciones que representa la situación es:

\begin{align*}
20x + 15y &= 150 \quad \text{(presupuesto total)} \\
x + y &= 10 \quad \text{(total de kilos de frutas)}
\end{align*}

Vamos a resolver este problema usando funciones en NumPy

In [14]:
# Escribimos la matriz asociada al sistema de ecuaciones
A = np.array([20, 15, 1, 1]).reshape((2,2)) # Va a convertir este vector en 2x2
A

array([[20, 15],
       [ 1,  1]])

In [15]:
# Vector de solución de sistema de ecuaciones
B = np.array([150,10])

$$AX=B$$

NumPy tiene una sublibrería que se llama Linalg en donde se pueden resolver sistemas de ecuaciones

In [16]:
# Solve resuelve el sistema de ecuaciones
X = np.linalg.solve(A,B)

X

array([ 0., 10.])

La solución al sistema de ecuaciones es x= 0 y y= 10